### PR TITLE
httpc: Avoid generating 'te' header

### PR DESCRIPTION
**Pull request by sinasamavati**

### CODE REVIEW

**Comment by qrilka** [comment]
Why do you just delete it? It's a valid header per se.
I think we should leave as it is

**Comment by pablohoffman** [comment]
@qrilka this is part of the work to emulate browsers behavior better, right? (which also includes the title case on headers). So we should do whatever browsers do, if browsers don't send the "te" header crawlera shouldn't either.

What I am not sure about is whether this should be omitted on OTP or suppressed on Crawlera side?. It's an implementation detail, but from a responsibility POV we should do it on Crawlera, since it's a crawlera specific requirement.

**Comment by sinasamavati** [comment]
@qrilka my commit message explains everything. I deleted it because I don't want httpc to generate the header automatically.

@pablohoffman In my humble opinion, it would be better to pick up an open-source http client, and make our changes on it if necessary.

**Comment by qrilka** [comment]
@s1n4 using other http lib is an option but I think that will change Crawlera much and will require extensive testing (our tests don't cover all of the scenarios unfortunately) so it's a point of another issue.
@pablohoffman we can't suppress that header on Crawlera level as it is set in httpc internally.
I think we should go other (and more compatible with OTP) way around: exclude empty "te" header added in https://github.com/scrapinghub/otp/blob/maint/lib/inets/src/http_client/httpc.erl#L1212
That will make the change a bit more logical and somewhat more "mainstream-compatible"
I have some vague motivation behind it in http://erlang.org/pipermail/erlang-questions/2010-April/050547.html

**Comment by sinasamavati** [comment]
Right.
I'm going to update this PR.

**Comment by sinasamavati** [comment]
Ping.

**Pull request merged**
