### PR TITLE
httpc: Avoid parsing invalid 'Set-Cookie' headers

### PR DESCRIPTION
**Pull request by sinasamavati**

### CODE REVIEW

**Comment by qrilka** [comment]
Please create PR to upstream

**Comment by qrilka** [comment]
And install new OTP version to buildbot slave (we use kerl)

**Comment by sinasamavati** [comment]
@qrilka please give me some information on what server buildbot runs, with what options you usually build OTP, etc.

**Comment by qrilka** [comment]
host `cislave01.dev.scrapinghub.com`, no special options and see `Makefile.buildbot` in Crawlera repo

**Comment by sinasamavati** [comment]
Done.

**Comment by qrilka** [comment]
And I see my patch applied also, perfect

**Pull request merged**
